import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  handProgress: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  row: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  communityCardsWrapper: {
    display: 'flex',
    alignItems: 'center',
    padding: 10,
    width: 750,
    height: 100,
    borderWidth: 2,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderColor: 'white',
  },
  actionIndicatorWrapper: {
    backgroundColor: 'red',
    display: 'flex',
    alignItems: 'center',
    padding: 10,
    width: 750,
    borderWidth: 2,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    borderTopWidth: 0,
    borderColor: 'white',
    marginBottom: 15,
  },
  actionIndicatorText: {
    textAlign: 'center',
    color: 'white',
    fontWeight: 'bold',
    fontSize: 25,
  },
  actionIndicatorTextWithBck: {
    textAlign: 'center',
    color: 'white',
    fontWeight: 'bold',
    fontSize: 25,
    backgroundColor: '#363D71',
    borderRadius: 5,
    marginBottom: 10,
  },
  undoButtonWrapper: {
    position: 'absolute',
    left: 0,
    bottom: 0,
  },
  missdealButtonWrapper: {
    position: 'absolute',
    right: 0,
    bottom: 0,
  },
  potIndicator: {
    position: 'absolute',
    left: 80,
    width: 180,
    top: 0,
  },
  effectiveActionIndiciator: {
    position: 'absolute',
    right: 80,
    width: 180,
    top: 0,
  },
  contentWrapper: {
    display: 'flex',
    flexDirection: 'row',
    width: '100%',
    height: '100%',
    backgroundColor: '#0D1321',
  },
  formWrapper: {
    width: '50%',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  numberPadWrapper: {
    width: '50%',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  playerStackInput: {
    color: 'black',
    backgroundColor: 'white',
    width: '80%',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: 'black',
    marginBottom: 10,
    fontSize: 18,
  },
  closeButtonWrapper: {
    position: 'absolute',
    top: 0,
    right: 0,
  },
  formRowWrapper: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  submitButtonWrapper: {
    display: 'flex',
    alignSelf: 'center',
  },
});
